# Test configuration for labeler
# This is a simplified version to test if the labeler works

documentation:
  - '**/*.md'

Backend:
  - '**/*.go'

Frontend:
  - 'web/**/*'

bug:
  - title: 'fix'
  - title: 'bug'

enhancement:
  - title: 'feat'
  - title: 'feature' 