apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: notifyops
  labels:
    app: web
    component: frontend
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
      component: frontend
  template:
    metadata:
      labels:
        app: web
        component: frontend
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
        prometheus.io/path: "/api/metrics"
    spec:
      serviceAccountName: notifyops-sa
      containers:
      - name: web
        image: notifyops-web:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        env:
        # Next.js Configuration
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: HOSTNAME
          value: "0.0.0.0"
        # API Configuration
        - name: NEXT_PUBLIC_API_URL
          value: "http://notifyops-service:8080"
        - name: NEXT_PUBLIC_METRICS_URL
          value: "http://notifyops-service:9090"
        - name: NEXT_PUBLIC_GRAFANA_URL
          value: "/grafana"
        # Build Configuration
        - name: NEXT_TELEMETRY_DISABLED
          value: "1"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false  # Next.js needs write access for build cache
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: next-cache
          mountPath: /app/.next/cache
          subPath: cache
        - name: next-cache
          mountPath: /app/node_modules/.cache
          subPath: node-cache
      volumes:
      - name: next-cache
        emptyDir: {}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30