apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: notifyops
  labels:
    app: web
    component: frontend
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
    prometheus.io/path: "/api/metrics"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
      appProtocol: http
  selector:
    app: web
    component: frontend
  sessionAffinity: None
---
# Optional: Service for static assets (if needed for CDN) #TODO: Remove this if not needed
apiVersion: v1
kind: Service
metadata:
  name: web-static-service
  namespace: notifyops
  labels:
    app: web
    component: static
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
      appProtocol: http
  selector:
    app: web
    component: frontend
  sessionAffinity: None
