apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: notifyops
  labels:
    app: prometheus
    component: storage
  annotations:
    description: "Persistent storage for Prometheus metrics data"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: notifyops
  labels:
    app: grafana
    component: storage
  annotations:
    description: "Persistent storage for Grafana dashboards and configurations"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard