apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: notifyops
  labels:
    app: grafana
    component: monitoring
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
    appProtocol: http
  selector:
    app: grafana
    component: monitoring
  sessionAffinity: None
---
# Optional: Service for Grafana API access (if needed for external integrations)
apiVersion: v1
kind: Service
metadata:
  name: grafana-api-service
  namespace: notifyops
  labels:
    app: grafana
    component: api
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
    appProtocol: http
  selector:
    app: grafana
    component: monitoring
  sessionAffinity: None