name: Build, Format, Lint, and Test

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  frontend:
    name: Frontend 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: web/package-lock.json

      - name: Install web dependencies
        working-directory: web
        run: npm ci

      - name: Install Playwright browsers
        working-directory: web
        run: npx playwright install

      - name: Check formatting (web)
        working-directory: web
        run: npm run format:check

      - name: Lint (web)
        working-directory: web
        run: npm run lint:check

      - name: Run web tests (not implemented yet 😭)
        working-directory: web
        run: echo "Have not fully implemented tests yet."

  backend:
    name: Backend 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Check formatting (Go)
        run: go fmt ./...

      - name: Build Go binary
        run: go build -o main ./cmd/server

      - name: Run Go tests (not implemented yet 😭)
        run: echo "Have not fully implemented tests yet."