name: Issue Bot

on:
  issue_comment:
    types: [created]
  issues:
    types: [opened, edited, reopened]
  pull_request:
    types: [opened, edited, reopened]
    branches: [main, ci]

jobs:
  issue-bot:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: read
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install @octokit/core @actions/github

      - name: Run the bot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          node .github/scripts/issue-bot.js
