# This workflow is based on github action official label action v4.
# This workflow action is triggered on pull request event(on both fork & inside repo)
# Labels will be applied based on filepath modification in PR.
# This workflow uses a regex based labeling config file(.github/labeler.yml) to take labeling decision.

name: "PR Labeler"
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
jobs:
  label:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run labeler
        uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: ".github/labeler.yml"
          sync-labels: false
