name: LGTM Label Check

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize, edited, reopened]
    branches: [main]

permissions:
  pull-requests: read
  issues: read

jobs:
  lgtm-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check for LGTM label
        uses: actions/github-script@v7
        with:
          script: |
            if (!context.payload.pull_request) {
              core.info('Not a pull_request event, skipping LGTM check.');
              return;
            }
            const labels = await github.rest.issues.listLabelsOnIssue({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number
            });
            const hasLgtm = labels.data.some(label => label.name.toLowerCase() === 'lgtm');
            if (!hasLgtm) {
              core.setFailed('PR must have the lgtm label to be merged.');
            } 